package com.example.model

enum class ClipType {
    VIDEO,
    QURAN,
    TEXT,
    AUDIO,
    IMAGE,
    STICKER,
    EFFECT
}

enum class QuranDisplayMode {
    ARABIC_AND_URDU,
    ARABIC_ONLY,
    URDU_ONLY
}

enum class TextAnimation {
    NONE,
    FADE_IN,
    FADE_OUT,
    SLIDE_UP,
    SLIDE_DOWN,
    SLIDE_LEFT,
    SLIDE_RIGHT,
    ZOOM_IN,
    ZOOM_OUT
}

enum class EffectType {
    BLUR,
    GLITCH,
    CINEMATIC_BARS,
    FADE,
    GLOW
}

enum class VideoFilter(val displayName: String) {
    NATURAL("Natural"),
    WARM("Warm"),
    VINTAGE("Vintage"),
    CINEMATIC("Cinematic"),
    BLACK_AND_WHITE("Black & White")
}

enum class CanvasRatio(val displayName: String, val aspectRatio: Float) {
    RATIO_9_16("9:16", 9f / 16f),
    RATIO_16_9("16:9", 16f / 9f),
    RATIO_1_1("1:1", 1f / 1f),
    RATIO_4_5("4:5", 4f / 5f)
}

data class VideoAdjustment(
    val brightness: Float = 0f,   // -0.5f .. 0.5f
    val contrast: Float = 1f,     // 0.5f .. 2.0f
    val saturation: Float = 1f,   // 0f .. 2.0f
    val exposure: Float = 0f,     // -0.5f .. 0.5f
    val temperature: Float = 0f,  // -0.5f .. 0.5f
    val vignette: Float = 0f      // 0f .. 1.0f
)

data class QuranStyle(
    val arabicFontSize: Float = 24f,
    val urduFontSize: Float = 16f,
    val arabicColorHex: Long = 0xFFFFFFFF,
    val urduColorHex: Long = 0xFFFCD34D,
    val strokeColorHex: Long = 0xFF000000,
    val shadowColorHex: Long = 0xCC000000,
    val backgroundColorHex: Long = 0x99000000,
    val backgroundOpacity: Float = 0.6f,
    val displayMode: QuranDisplayMode = QuranDisplayMode.ARABIC_AND_URDU,
    val isBold: Boolean = true,
    val lineSpacing: Float = 1.2f
)

data class VideoClip(
    val id: String,
    val uri: String? = null,
    val name: String = "Video",
    val startTrimMs: Long = 0L,
    val endTrimMs: Long = 10000L,
    val timelineStartMs: Long = 0L,
    val timelineEndMs: Long = 10000L,
    val originalDurationMs: Long = 10000L,
    val volume: Float = 1f,
    val isMuted: Boolean = false,
    val speed: Float = 1f
) {
    val durationMs: Long get() = timelineEndMs - timelineStartMs
}

data class QuranClip(
    val id: String,
    val surahNumber: Int,
    val surahName: String,
    val ayahNumber: Int,
    val arabicText: String,
    val urduTranslation: String,
    val timelineStartMs: Long,
    val timelineEndMs: Long,
    val posX: Float = 0f,        // -1f .. 1f
    val posY: Float = 0.45f,     // -1f .. 1f
    val style: QuranStyle = QuranStyle(),
    val confidence: Float = 1.0f,
    val isAutoGenerated: Boolean = false
) {
    val durationMs: Long get() = timelineEndMs - timelineStartMs
}

data class TextClip(
    val id: String,
    val text: String,
    val timelineStartMs: Long,
    val timelineEndMs: Long,
    val fontSize: Float = 22f,
    val colorHex: Long = 0xFFFFFFFF,
    val isBold: Boolean = true,
    val isItalic: Boolean = false,
    val posX: Float = 0f,
    val posY: Float = 0f,
    val scale: Float = 1f,
    val rotation: Float = 0f,
    val animation: TextAnimation = TextAnimation.NONE,
    val backgroundColorHex: Long = 0x00000000,
    val opacity: Float = 1f
) {
    val durationMs: Long get() = timelineEndMs - timelineStartMs
}

data class AudioClip(
    val id: String,
    val uri: String? = null,
    val name: String = "Audio",
    val timelineStartMs: Long,
    val timelineEndMs: Long,
    val startTrimMs: Long = 0L,
    val volume: Float = 1f,
    val isMuted: Boolean = false,
    val fadeInMs: Long = 0L,
    val fadeOutMs: Long = 0L
) {
    val durationMs: Long get() = timelineEndMs - timelineStartMs
}

data class ImageClip(
    val id: String,
    val uri: String,
    val timelineStartMs: Long,
    val timelineEndMs: Long,
    val posX: Float = 0f,
    val posY: Float = -0.3f,
    val scale: Float = 1f,
    val rotation: Float = 0f,
    val opacity: Float = 1f
) {
    val durationMs: Long get() = timelineEndMs - timelineStartMs
}

data class StickerClip(
    val id: String,
    val stickerId: String,
    val symbol: String,
    val label: String,
    val timelineStartMs: Long,
    val timelineEndMs: Long,
    val posX: Float = 0f,
    val posY: Float = -0.3f,
    val scale: Float = 1f,
    val opacity: Float = 1f
) {
    val durationMs: Long get() = timelineEndMs - timelineStartMs
}

data class EffectClip(
    val id: String,
    val type: EffectType,
    val timelineStartMs: Long,
    val timelineEndMs: Long,
    val intensity: Float = 1f
) {
    val durationMs: Long get() = timelineEndMs - timelineStartMs
}

data class EditorProjectState(
    val videoClips: List<VideoClip> = emptyList(),
    val quranClips: List<QuranClip> = emptyList(),
    val textClips: List<TextClip> = emptyList(),
    val audioClips: List<AudioClip> = emptyList(),
    val imageClips: List<ImageClip> = emptyList(),
    val stickerClips: List<StickerClip> = emptyList(),
    val effectClips: List<EffectClip> = emptyList(),
    val filter: VideoFilter = VideoFilter.NATURAL,
    val adjustment: VideoAdjustment = VideoAdjustment(),
    val canvasRatio: CanvasRatio = CanvasRatio.RATIO_9_16,
    val speed: Float = 1f,
    val currentTimeMs: Long = 0L,
    val durationMs: Long = 10000L,
    val isPlaying: Boolean = false,
    val selectedClipId: String? = null,
    val selectedClipType: ClipType? = null,
    val isMuted: Boolean = false,
    val volume: Float = 1f
)
